# StorageClass for PostgreSQL (CloudNativePG) - NFS with mapall omitted
# Empty nfs.mapAllUser/nfs.mapAllGroup omits mapall from the NFS export.
# Non-root client UIDs (e.g. postgres UID 26) preserve identity on the server.
# No TrueNAS user creation required.
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-csi-nfs-no-mapall
provisioner: csi.truenas.io
parameters:
  protocol: "nfs"
  pool: "tank"
  compression: "LZ4"
  nfs.mapAllUser: ""
  nfs.mapAllGroup: ""
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
